"""
PDF report generation for optimized portfolios.
"""
from __future__ import annotations

import io
from datetime import datetime
from fpdf import FPDF


def _sanitize(text: str) -> str:
    """Sanitize text for fpdf2 Latin-1 font support."""
    replacements = {
        "\u2014": "--",
        "\u2013": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2026": "...",
        "\u2022": "*",
        "\u00b7": "*",
        "\u2192": "->",
        "\u2190": "<-",
        "\u2265": ">=",
        "\u2264": "<=",
        "\u00b0": " deg",
        "\u2103": " C",
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    try:
        text.encode("latin-1")
    except UnicodeEncodeError:
        text = text.encode("latin-1", errors="replace").decode("latin-1")
    return text


def generate_portfolio_report(portfolio: dict, securities: list[dict]) -> bytes:
    """Generate a PDF report for an optimized portfolio."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 12, _sanitize("ESG Portfolio Report"), new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, _sanitize(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}"), new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.cell(0, 6, _sanitize("ESG & Thematic Investment Screener | Nhat Nguyen"), new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(10)

    # Portfolio Summary
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, _sanitize("Portfolio Summary"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)

    obj_label = {
        "max_sharpe": "Maximize Sharpe Ratio",
        "min_variance": "Minimize Variance",
        "max_esg": "Maximize ESG Score",
    }.get(portfolio.get("objective_used", ""), "Unknown")

    summary_lines = [
        f"Objective: {obj_label}",
        f"Expected Annual Return: {portfolio['expected_return']:.2%}",
        f"Annual Volatility: {portfolio['volatility']:.2%}",
        f"Sharpe Ratio: {portfolio['sharpe_ratio']:.2f}",
        f"Portfolio ESG Score: {portfolio['portfolio_esg_score']:.1f} / 100",
        f"Portfolio Carbon Intensity: {portfolio['portfolio_carbon_intensity']:.1f} tCO2e/$M",
    ]
    for line in summary_lines:
        pdf.cell(0, 7, _sanitize(line), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Allocation Table
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, _sanitize("Portfolio Allocation"), new_x="LMARGIN", new_y="NEXT")

    # Table header
    pdf.set_font("Helvetica", "B", 9)
    col_widths = [25, 55, 30, 25, 25, 30]
    headers = ["Ticker", "Name", "Weight", "Sector", "ESG", "Carbon"]
    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], 8, _sanitize(h), border=1)
    pdf.ln()

    # Table rows
    pdf.set_font("Helvetica", "", 9)
    sec_map = {s["ticker"]: s for s in securities}
    for alloc in portfolio.get("weights", []):
        ticker = alloc["ticker"]
        sec = sec_map.get(ticker, {})
        row = [
            ticker,
            alloc.get("name", sec.get("name", ticker))[:28],
            f"{alloc['weight']:.1%}",
            alloc.get("sector", sec.get("sector", ""))[:12],
            str(int(sec.get("esg_overall", alloc.get("esg_score", 0)))),
            str(int(sec.get("carbon_intensity", 0))),
        ]
        for i, val in enumerate(row):
            pdf.cell(col_widths[i], 7, _sanitize(val), border=1)
        pdf.ln()

    pdf.ln(8)

    # Disclaimer
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(0, 5, _sanitize(
        "Disclaimer: This report is for educational and demonstration purposes only. "
        "ESG data is illustrative and should not be used for actual investment decisions. "
        "Past performance does not guarantee future results. "
        "Generated by ESG & Thematic Investment Screener by Nhat Nguyen."
    ))

    return bytes(pdf.output())
